---
baseURL: "https://troubleshoot.sh/"
languageCode: "en-us"
title: "Troubleshoot.sh"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
relativeurls: true
description: "Documentation for the kubectl troubleshoot plugin"
googleAnalytics: ""

# Algoloia search
algolia:
  index: "prod_troubleshoot"
  appID: "NHTIKUBZ4C"

# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

staticDir:
    - ./static

Params:
  author: "Troubleshoot.sh"
  copyright: "Replicated, Inc"
  homepage_intro: "Deliver More Reliable and Predictable Kubernetes Applications"
  # matomo:
  #   host: "localhost:4000"
  #   site: "2"

  enable_anchor_link: true
  favicon: ""
  logo:
    preflight: "/images/preflight.svg"
    support_bundle: "/images/support.svg"
  pagetitle: "Troubleshoot.sh"
  permalink: "#"
  mainSections:
    - preflight
    - support-bundle
    - reference
menu:
  main:
    - Name: Preflight
      Identifier: preflight
      Weight: 1
      URL: /preflight/overview/
    - Name: Support Bundle
      Identifier: support-bundle
      Weight: 2
      URL: /support-bundle/overview/
    - Name: Reference
      Identifier: reference
      Weight: 3
      URL: /reference/getting-started/overview
---
