---
baseURL: "https://troubleshoot-sh.netlify.com"
languageCode: "en-us"
title: "Troubleshoot.sh"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation for the kubectl troubleshoot plugin"
googleAnalytics: ""


# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

staticDir:
    - ./static

Params:
  author: "Troubleshoot.sh"
  copyright: "Replicated, Inc"
  homepage_intro: "Troubleshoot is a kubectl plugin to run preflights or generate easy-to-read support bundles for Kots applications"

  # matomo:
  #   host: "localhost:4000"
  #   site: "2"

  favicon: ""
  logo:
    preflight: "/images/preflight.svg"
    support_bundle: "/images/support.svg"
  pagetitle: "Troubleshoot.sh"
  permalink: "#"
  mainSections:
    - preflight
    - support-bundle
menu:
  main:
    - Name: "Preflight"
      Weight: 1
      URL: "/preflight/"
    - Name: "Support Bundle"
      Weight: 2
      URL: "/support-bundle/"
---
